name: Build TGX

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Run...
      run: |
        apt update
        apt upgrade
        apt install git git-lfs
        git clone --recursive --depth=1 --shallow-submodules https://github.com/TGX-Android/Telegram-X tgx
        cd tgx
        scripts/./setup.sh
        cd ..
        chmod +x gradle
        ./gradlew assembleUniversalRelease
